apiVersion: ocmirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
mirror:
  ocp:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8
      headsOnly: false
      packages:
        - name: elasticsearch-operator
          startingVersion: '5.2.3-31'
